### ISSUE TITLE
Incorrect conversion for System.Drawing.Imaging.PixelFormat.Format32bppArgb

### ISSUE THREAD

**Issue by aaviants** [mathieumack/PixelFormatsConverter#2]
Greetings,

Thank you for the conversion utility, it really helps.
I used it in my app and found the following misalignments for System.Drawing.Imaging.PixelFormat.Format32bppArgb <-> System.Windows.Media.PixelFormats.Bgra32 formats (conversion back and forth).

There should be 
`
if (pixelFormat == System.Drawing.Imaging.PixelFormat.Format32bppArgb)
    return System.Windows.Media.PixelFormats.Bgra32;
`
instead of 
`
if (pixelFormat == System.Drawing.Imaging.PixelFormat.Format32bppArgb)
    return System.Windows.Media.PixelFormats.Bgr32;
`
and there should be
`
if (pixelFormat == System.Windows.Media.PixelFormats.Bgra32)
    return System.Drawing.Imaging.PixelFormat.Format32bppArgb;
`
instead of
`
if (pixelFormat == System.Windows.Media.PixelFormats.Bgr32)
    return System.Drawing.Imaging.PixelFormat.Format32bppArgb;
`

**Comment by mathieumack** [comment]
Hi, thanks for your feedback.
I will try to fix it quickly.

**Comment by mathieumack** [comment]
@aaviants ,

Hi,
A preview version can be downloaded (https://www.nuget.org/packages/PixelFormatsConverter/1.0.0-preview1).
You can check quickly the PR to ensure that the fix is ok.

Once you validate the fix (link to the extension : https://github.com/mathieumack/PixelFormatsConverter/pull/3/files#diff-ab199ab11a2d7517278b40a2e9e17be5e2b4a20faf4ae4f5c87545bc037beb51), I will publish a stable version to nuget.

**Comment by aaviants** [comment]
Thank you @mathieumack for the prompt fix.
I've reviewed changes in [PixelFormatConverterExtensions.cs](https://github.com/mathieumack/PixelFormatsConverter/pull/3/files#diff-ab199ab11a2d7517278b40a2e9e17be5e2b4a20faf4ae4f5c87545bc037beb51) file and those look good to me.

**Comment by mathieumack** [comment]
@aaviants 
A new stable version is now published :
https://www.nuget.org/packages/PixelFormatsConverter/1.0.0

Have a nice day.
